# A completely self-contained configuration using a bundled
# postgres database and a single hard-coded user.
#
# Useful for prototyping or local development with no available
# infrastructure. Container ports are mapped to the range 3000-3002.
#
# **NOTE**: If you want to have multiple users or integrate your own
#           external IdP, please start from the `keycloak` example
#           instead.

services:
  app:
    image: ghcr.io/tenzir/app:${TENZIR_PLATFORM_VERSION:-latest}
    build: ../../components/app
    environment:
      - AUTH_TRUST_HOST=true
      - PUBLIC_ENABLE_HIGHLIGHT=false
      - ORIGIN=${TENZIR_PLATFORM_UI_ENDPOINT}
      - PRIVATE_OIDC_PROVIDER_NAME=tenzir
      - PRIVATE_OIDC_PROVIDER_CLIENT_ID=tenzir-app
      - PRIVATE_OIDC_PROVIDER_CLIENT_SECRET=xxxx
      - PRIVATE_OIDC_PROVIDER_ISSUER_URL=http://platform:5000/oidc
      - PUBLIC_OIDC_PROVIDER_ID=tenzir
      - PUBLIC_WEBSOCKET_GATEWAY_ENDPOINT=${TENZIR_PLATFORM_NODES_ENDPOINT}
      - PRIVATE_USER_ENDPOINT=http://platform:5000/user
      - PRIVATE_WEBAPP_ENDPOINT=http://platform:5000/webapp
      - PRIVATE_WEBAPP_KEY=${TENZIR_PLATFORM_INTERNAL_APP_API_KEY}
      - AUTH_SECRET=${TENZIR_PLATFORM_INTERNAL_AUTH_SECRET}
      - PUBLIC_DISABLE_DEMO_NODE_AND_TOUR=${TENZIR_PLATFORM_DISABLE_LOCAL_DEMO_NODES}
      - PRIVATE_DRIZZLE_DATABASE_URL=postgres://${TENZIR_PLATFORM_POSTGRES_USER}:${TENZIR_PLATFORM_POSTGRES_PASSWORD}@${TENZIR_PLATFORM_POSTGRES_HOSTNAME}/${TENZIR_PLATFORM_POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  platform:
    image: ghcr.io/tenzir/platform:${TENZIR_PLATFORM_VERSION}
    build: ../../components/tenant-manager/platform/tenant_manager/
    command: ["tenant_manager/rest/server/local.py"]
    environment:
      - BASE_PATH=
      - GATEWAY_WS_ENDPOINT=${TENZIR_PLATFORM_NODES_ENDPOINT}
      - GATEWAY_HTTP_ENDPOINT=http://websocket-gateway:5000
      - TENANT_MANAGER_DISABLE_LOCAL_DEMO_NODES=${TENZIR_PLATFORM_DISABLE_LOCAL_DEMO_NODES}
      - TENZIR_DEMO_NODE_IMAGE=${TENZIR_PLATFORM_DEMO_NODE_IMAGE:-tenzir/tenzir-demo:latest}
      - TENANT_MANAGER_APP_API_KEY=${TENZIR_PLATFORM_INTERNAL_APP_API_KEY}
      - TENANT_MANAGER_TENANT_TOKEN_ENCRYPTION_KEY=${TENZIR_PLATFORM_INTERNAL_TENANT_TOKEN_ENCRYPTION_KEY}
      - TENANT_MANAGER_AUTH__SINGLE_USER_MODE=true
      - TENANT_MANAGER_AUTH__ISSUER_URL=http://platform:5000/oidc
      - TENANT_MANAGER_AUTH__PUBLIC_BASE_URL=${TENZIR_PLATFORM_API_ENDPOINT}/oidc
      - TENANT_MANAGER_AUTH__APP_AUDIENCE=tenzir-app
      - TENANT_MANAGER_AUTH__APP_REDIRECT_URLS=${TENZIR_PLATFORM_UI_ENDPOINT}/login/oauth/callback,http://localhost:3000/login/oauth/callback,http://localhost:5173/login/oauth/callback
      - TENANT_MANAGER_AUTH__CLI_AUDIENCE=tenzir-cli
      - TENANT_MANAGER_AUTH__ADMIN_FUNCTIONS=${TENZIR_PLATFORM_ADMIN_RULES}
      - STORE__TYPE=postgres
      - STORE__POSTGRES_URI=postgresql://${TENZIR_PLATFORM_POSTGRES_USER}:${TENZIR_PLATFORM_POSTGRES_PASSWORD}@${TENZIR_PLATFORM_POSTGRES_HOSTNAME}/${TENZIR_PLATFORM_POSTGRES_DB}
      # seaweedfs s3 connection
      - TENANT_MANAGER_SIDEPATH_BUCKET_NAME=${TENZIR_PLATFORM_INTERNAL_BUCKET_NAME}
      - BLOB_STORAGE__ENDPOINT_URL=http://seaweed:8333
      - BLOB_STORAGE__PUBLIC_ENDPOINT_URL=${TENZIR_PLATFORM_DOWNLOADS_ENDPOINT}
      - BLOB_STORAGE__ACCESS_KEY_ID=${TENZIR_PLATFORM_INTERNAL_ACCESS_KEY_ID}
      - BLOB_STORAGE__SECRET_ACCESS_KEY=${TENZIR_PLATFORM_INTERNAL_SECRET_ACCESS_KEY}
      - WORKSPACE_CONFIG_FILE=/etc/tenzir/workspaces.yaml
      - WORKSPACE_SECRETS_MASTER_SEED=${TENZIR_PLATFORM_INTERNAL_MASTER_SEED}
    volumes:
      - ./workspaces.yaml:/etc/tenzir/workspaces.yaml
      # Mounting the docker socket is required iff local demo nodes are enabled.
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:5000
    depends_on:
      websocket-gateway:
        condition: service_started
      postgres:
        condition: service_healthy

  websocket-gateway:
    image: ghcr.io/tenzir/platform:${TENZIR_PLATFORM_VERSION:-latest}
    build: ../../components/tenant-manager/platform/tenant_manager/
    command: ["tenant_manager/ws/server/local.py"]
    environment:
      - BASE_PATH=
      - TENZIR_PROXY_TIMEOUT=60
      - TENANT_MANAGER_APP_API_KEY=${TENZIR_PLATFORM_INTERNAL_APP_API_KEY}
      - TENANT_MANAGER_TENANT_TOKEN_ENCRYPTION_KEY=${TENZIR_PLATFORM_INTERNAL_TENANT_TOKEN_ENCRYPTION_KEY}
      - TENZIR_PLATFORM_METRICS_STORE_S3_BUCKET_NAME=${TENZIR_PLATFORM_METRICS_STORE_S3_BUCKET_NAME:-tenzir-node-metrics}
      - STORE__TYPE=postgres
      - STORE__POSTGRES_URI=postgresql://${TENZIR_PLATFORM_POSTGRES_USER}:${TENZIR_PLATFORM_POSTGRES_PASSWORD}@${TENZIR_PLATFORM_POSTGRES_HOSTNAME}/${TENZIR_PLATFORM_POSTGRES_DB}
      - BLOB_STORAGE__ENDPOINT_URL=http://seaweed:8333
      - BLOB_STORAGE__PUBLIC_ENDPOINT_URL=${TENZIR_PLATFORM_BLOBS_ENDPOINT}
      - BLOB_STORAGE__ACCESS_KEY_ID=${TENZIR_PLATFORM_INTERNAL_ACCESS_KEY_ID}
      - BLOB_STORAGE__SECRET_ACCESS_KEY=${TENZIR_PLATFORM_INTERNAL_SECRET_ACCESS_KEY}
      - WORKSPACE_SECRETS_MASTER_SEED=${TENZIR_PLATFORM_INTERNAL_MASTER_SEED}
    depends_on:
      postgres:
        condition: service_healthy
      seaweed:
        condition: service_started
    ports:
      - 3002:5000

  # Use like `docker compose run --rm cli --help`
  cli:
    image: ghcr.io/tenzir/tenzir-platform:${TENZIR_PLATFORM_VERSION:-latest}
    build: ../../cli/
    profiles:
      - donotstart
    volumes:
      - cli_cache:/cache/tenzir-platform
    environment:
      - XDG_CACHE_HOME=/cache/
      - TENZIR_PLATFORM_CLI_API_ENDPOINT=http://platform:5000/
      - TENZIR_PLATFORM_CLI_ISSUER_URL=http://platform:5000/oidc
      # Hard-coded client secret and id, because we're running the
      # platform in single-user mode.
      - TENZIR_PLATFORM_CLI_CLIENT_ID=tenzir-cli
      - TENZIR_PLATFORM_CLI_CLIENT_SECRET=xxxx

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=${TENZIR_PLATFORM_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TENZIR_PLATFORM_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TENZIR_PLATFORM_POSTGRES_DB}
      # For psql, so you can run `docker compose exec postgres psql`.
      - PGUSER=${TENZIR_PLATFORM_POSTGRES_USER}
      - PGDATABASE=${TENZIR_PLATFORM_POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U postgres'
      interval: 10s
      timeout: 5s
      retries: 5

  # Note the ~25 seconds startup delay before the seaweed server
  # becomes ready.
  seaweed:
    image: ghcr.io/tenzir/tenzir-seaweed:${TENZIR_PLATFORM_VERSION:-latest}
    build: ../../components/seaweed/
    environment:
      - TENZIR_PLATFORM_INTERNAL_ACCESS_KEY_ID
      - TENZIR_PLATFORM_INTERNAL_SECRET_ACCESS_KEY
    command: ["server", "-dir=/var/lib/seaweedfs", "-s3", "-s3.config=/config.json"]
    volumes:
      - seaweed_data:/var/lib/seaweedfs
    ports:
      - '3003:8333'
      - '9333:9333'

  node:
    image: ghcr.io/tenzir/tenzir-node:main
    environment:
      - TENZIR_TOKEN=wsk_e9ee76d4faf4b213745dd5c99a9be11f501d7009ded63f2d5NmDS38vXR
      - TENZIR_NODE_NAME=localdev
      - TENZIR_PLATFORM_NODES_ENDPOINT=ws://websocket-gateway:5000
    depends_on:
      websocket-gateway:
        condition: service_started

volumes:
  postgres_data:
    driver: local
  seaweed_data:
    driver: local
