{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenzir-platform.fullname" . }}-api
  labels:
    {{- include "tenzir-platform.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tenzir-platform.api.selectorLabels" . | nindent 4 }}
{{- end }}