{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenzir-platform.fullname" . }}-ui
  labels:
    {{- include "tenzir-platform.ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "tenzir-platform.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tenzir-platform.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tenzir-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}"
          imagePullPolicy: {{ .Values.images.ui.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: AUTH_TRUST_HOST
              value: "{{ .Values.ui.env.AUTH_TRUST_HOST }}"
            - name: PUBLIC_ENABLE_HIGHLIGHT
              value: "{{ .Values.ui.env.PUBLIC_ENABLE_HIGHLIGHT }}"
            - name: PUBLIC_DISABLE_DEMO_NODE_AND_TOUR
              value: "{{ .Values.ui.env.PUBLIC_DISABLE_DEMO_NODE_AND_TOUR }}"
            - name: ORIGIN
              value: "https://{{ include "tenzir-platform.uiDomain" . }}"
            - name: PRIVATE_OIDC_PROVIDER_NAME
              value: "{{ .Values.ui.env.PRIVATE_OIDC_PROVIDER_NAME }}"
            - name: PUBLIC_OIDC_PROVIDER_ID
              value: "{{ .Values.ui.env.PUBLIC_OIDC_PROVIDER_ID }}"
            - name: PUBLIC_OIDC_SCOPES
              value: "{{ .Values.ui.env.PUBLIC_OIDC_SCOPES }}"
            - name: PRIVATE_OIDC_PROVIDER_CLIENT_ID
              value: "{{ .Values.auth.oidc.clientId }}"
            - name: PRIVATE_OIDC_PROVIDER_ISSUER_URL
              value: "{{ .Values.auth.oidc.issuerUrl }}"
            - name: PUBLIC_WEBSOCKET_GATEWAY_ENDPOINT
              value: "wss://{{ include "tenzir-platform.nodesDomain" . }}"
            - name: PRIVATE_USER_ENDPOINT
              value: "https://{{ include "tenzir-platform.apiDomain" . }}/user"
            - name: PRIVATE_WEBAPP_ENDPOINT
              value: "https://{{ include "tenzir-platform.apiDomain" . }}/webapp"
            {{- if .Values.auth.oidc.clientSecret }}
            - name: PRIVATE_OIDC_PROVIDER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-client-secret
                  key: client-secret
            {{- end }}
            - name: PRIVATE_WEBAPP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.tenantManager.appApiKey.name }}
                  key: {{ .Values.secrets.tenantManager.appApiKey.key }}
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.auth.name }}
                  key: {{ .Values.secrets.auth.secretKey }}
            - name: PRIVATE_DRIZZLE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres.name }}
                  key: {{ .Values.secrets.postgres.uriKey }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}