#!/bin/bash

SUBMODULE_PATH="$1"
FROM_COMMIT="$2"
TO_COMMIT="$3"

CHANGELOG_BASE64=$(git -C ${SUBMODULE_PATH} log --stat ${FROM_COMMIT}..${TO_COMMIT} | base64 -w 0)

REQUEST_JSON=$(cat <<EOF
{
  "contents": {
    "role": "user",
    "parts": [
      {"text": "Please output a brief summary of the changes that were made in the attached git log. Use roughly one sentence per independent feature or bugfix introduced. Focus on on the user-visible effect and not the technical implementation details."},
      {"inlineData": {"mimeType": "text/plain", "data": "${CHANGELOG_BASE64}"}},
    ],
  }
}
EOF
)

echo ${REQUEST_JSON} >&2
echo "Access token length: ${#GCLOUD_ACCESS_TOKEN}" >&2
echo "Access token first four chars: ${GCLOUD_ACCESS_TOKEN:0:4}" >&2

RESPONSE=$(curl -s --fail -X POST \
  -H "Authorization: Bearer ${GCLOUD_ACCESS_TOKEN}" \
  -H "Content-Type: application/json" \
  https://${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/${LOCATION}/publishers/google/models/${MODEL}:generateContent \
  -d "${REQUEST_JSON}")

if [ $? -eq 0 ]; then
  echo ${RESPONSE} | jq -r .candidates[0].content.parts[0].text
else
  echo $(git -C ${SUBMODULE_PATH} log --oneline --first-parent --no-decorate ${FROM_COMMIT}..${TO_COMMTI})
fi
echo "\n\nView Changes: https://github.com/tenzir/app/compare/${current_sha}...${upstream_sha}"
