name: Build and Push Containers to GitHub Container Registry

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: tenzir-dex
          registry: ghcr.io
          directory: components/dex
          dockerfile: components/dex/Dockerfile
          addLatest: ${{ github.event_name == 'release' }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: tenzir-seaweed
          registry: ghcr.io
          directory: components/seaweed
          dockerfile: components/seaweed/Dockerfile
          addLatest: ${{ github.event_name == 'release' }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
