name: Bump component submodules

on:
  workflow_call:
    inputs:
      bump-app:
        description: Bump the app submodule
        type: boolean
        default: true
      bump-tenant-manager:
        description: Bump the tenant manager submodule
        type: boolean
        default: true


jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TENZIR_APP_DEPLOY_KEY }}
      - name: Update app submodule
        if: ${{ inputs.bump-app }}
        run: |
          git submodule update --init components/app
          current_sha=$(git -C components/app rev-parse HEAD)
          upstream_sha=$(git -C components/app rev-parse origin/main)
          if [ ${current_sha} != ${upstream_sha} ]; then
            # Collect all files in the `changelog` directory that
            # were added since the last bump.
            names=$(git -C components/app diff --name-status HEAD origin/main -- changelog/ | grep '^A' | awk '{print $2}')
            echo -e "Bump app component from ${current_sha} to ${upstream_sha}\n\nChanges:\n" > commitmsg
            for name in ${names}; do
              cat components/app/${name} >> commitmsg
            done
            git -C components/app rebase origin/main
            git add components/app
            git commit -F commitmsg
            git push
          fi
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TENZIR_EVENT_HORIZON_DEPLOY_KEY }}
      - name: Update tenant-manager submodule
        if: ${{ inputs.bump-tenant-manager }}
        run: |
          git submodule update --init components/tenant-manager
          current_sha=$(git -C components/tenant-manager rev-parse main)
          upstream_sha=$(git -C components/tenant-manager rev-parse origin/main)
          if [ ${current_sha} != ${upstream_sha} ]; then
            names=$(git -C components/tenant-manager diff --name-status HEAD origin/main -- changelog/ | grep '^A' | awk '{print $2}')
            echo -e "Bump tenant-manager component from ${current_sha} to ${upstream_sha}\n\nChanges:\n" > commitmsg
            for name in ${names}; do
              cat components/tenant-manager/${name} >> commitmsg
            done
            git -C components/tenant-manager rebase origin/main
            git add components/tenant-manager
            git commit -F commitmsg
            git push
          fi

